# Generated by Django 5.0.4 on 2024-05-13 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery_app', '0002_alter_category_options_alter_photo_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Category'},
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Photo'},
        ),
    ]
