# Generated by Django 4.2.14 on 2024-07-22 14:55

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreateEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=60)),
                ('event_created_date', models.DateField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Create New Event',
                'db_table': 'Create New Event',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('sub_title', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('event_image', models.ImageField(blank=True, null=True, upload_to='images/event/')),
                ('brief', tinymce.models.HTMLField()),
                ('hide', models.BooleanField()),
                ('created_events', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='event_app.createevent')),
            ],
            options={
                'verbose_name_plural': 'Event',
                'db_table': 'Event',
                'ordering': ['-id'],
            },
        ),
    ]
