# Generated by Django 5.0.4 on 2024-04-17 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('event_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('brief_1', models.TextField()),
                ('brief_2', models.TextField(blank=True, null=True)),
                ('brief_3', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
