# Generated by Django 5.0.4 on 2024-04-18 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0003_event_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Event_Creator',
                'db_table': 'Event_Creator',
            },
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_name',
        ),
        migrations.AddField(
            model_name='event',
            name='created_events',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='event_app.createevent'),
        ),
    ]
