# Generated by Django 5.0.4 on 2024-04-19 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0004_createevent_remove_event_event_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='created_time',
        ),
        migrations.AddField(
            model_name='event',
            name='created_date',
            field=models.DateField(auto_created=True, null=True),
        ),
    ]
