# Generated by Django 5.0.4 on 2024-04-19 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0005_remove_event_created_time_event_created_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='createevent',
            old_name='event_name',
            new_name='name',
        ),
    ]
