# Generated by Django 5.0.4 on 2024-04-27 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0007_rename_brief_1_event_brief_remove_event_brief_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='postal_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
