# Generated by Django 5.0.4 on 2024-05-16 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0013_alter_createevent_options_alter_event_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_image',
            field=models.ImageField(blank=True, null=True, upload_to='event_images'),
        ),
    ]
