# Generated by Django 5.0.3 on 2024-05-26 17:10

import phonenumber_field.modelfields
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_created=True, auto_now=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.IntegerField()),
                ('address_1', models.CharField(max_length=200)),
                ('address_2', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(max_length=400)),
                ('state', models.CharField(max_length=400)),
                ('postal_code', models.IntegerField()),
                ('country', models.CharField(max_length=200)),
                ('donation_type', models.CharField(choices=[('GENERAL', 'general'), ('COVID', 'covid'), ('EARTHQUAKE', 'earthquake')], max_length=12)),
                ('amount', models.IntegerField()),
                ('screenshot', models.ImageField(upload_to='images/payments/donation/')),
                ('status', models.CharField(choices=[('C', 'Confirmed'), ('U', 'Unconfirm')], default='U', max_length=1)),
            ],
            options={
                'verbose_name_plural': 'Donation',
                'db_table': 'Donation',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=15)),
                ('feedback', models.TextField()),
                ('status', models.CharField(choices=[('R', 'Read'), ('U', 'Unread')], default='U', max_length=1)),
            ],
            options={
                'verbose_name_plural': 'Contact',
                'db_table': 'Contact',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('contact', phonenumber_field.modelfields.PhoneNumberField(help_text='your contact number', max_length=13, region=None)),
                ('address1', models.CharField(max_length=200)),
                ('address2', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(max_length=400)),
                ('province', models.CharField(max_length=400)),
                ('postal_code', models.IntegerField()),
                ('membership', models.CharField(choices=[('GENERAL', 'general'), ('LIFETIME', 'lifetime')], default='GENERAL', max_length=9)),
                ('screenshot', models.ImageField(upload_to='images/payments/membership/')),
                ('status', models.CharField(choices=[('C', 'Confirmed'), ('U', 'Unconfirm')], default='U', max_length=1)),
            ],
            options={
                'verbose_name_plural': 'Member',
                'db_table': 'Member',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=200)),
                ('c_date', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/vacancy/')),
                ('vacancy_content', tinymce.models.HTMLField(null=True)),
            ],
            options={
                'verbose_name_plural': 'vacancy',
                'db_table': 'Vacancy',
                'ordering': ['-id'],
            },
        ),
    ]
