# Generated by Django 4.2.14 on 2024-07-22 14:55

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_created=True, auto_now=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=254)),
                ('address_1', models.CharField(max_length=200)),
                ('address_2', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(max_length=400)),
                ('state', models.CharField(max_length=400)),
                ('postal_code', models.CharField(max_length=15)),
                ('country', models.CharField(max_length=200)),
                ('donation_type', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
                ('screenshot', models.ImageField(upload_to='images/payments/donation/')),
                ('status', models.CharField(choices=[('C', 'Confirmed'), ('U', 'Unconfirm')], default='U', max_length=1)),
            ],
            options={
                'verbose_name_plural': 'Donation',
                'db_table': 'Donation',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='DonationInstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruct', tinymce.models.HTMLField()),
            ],
            options={
                'verbose_name_plural': 'Donation Instruction',
                'db_table': 'Donation Instruction',
            },
        ),
        migrations.CreateModel(
            name='DonationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('hide', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'Donation Type',
                'db_table': 'Donation Type',
            },
        ),
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=18)),
                ('feedback', models.TextField()),
                ('status', models.CharField(choices=[('R', 'Read'), ('U', 'Unread')], default='U', max_length=1)),
            ],
            options={
                'verbose_name_plural': 'Feedback',
                'db_table': 'Feedback',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackInstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruct', tinymce.models.HTMLField()),
            ],
            options={
                'verbose_name_plural': 'Feedback Instruction',
                'db_table': 'Feedback Instruction',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=18)),
                ('address1', models.CharField(max_length=200)),
                ('address2', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(max_length=50)),
                ('province', models.CharField(max_length=50)),
                ('postal_code', models.CharField(max_length=15)),
                ('membership', models.CharField(max_length=90)),
                ('screenshot', models.ImageField(upload_to='images/payments/membership/')),
                ('status', models.CharField(choices=[('C', 'Confirmed'), ('U', 'Unconfirm')], default='U', max_length=1)),
            ],
            options={
                'verbose_name_plural': 'Member',
                'db_table': 'Member',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='MemberInstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruct', tinymce.models.HTMLField()),
            ],
            options={
                'verbose_name_plural': 'Member Instruction',
                'db_table': 'Member Instruction',
            },
        ),
        migrations.CreateModel(
            name='MemberType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('hide', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'Member Type',
                'db_table': 'Member Type',
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=200)),
                ('c_date', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/vacancy/')),
                ('vacancy_content', tinymce.models.HTMLField(null=True)),
            ],
            options={
                'verbose_name_plural': 'vacancy',
                'db_table': 'Vacancy',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='VacancyInstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruct', tinymce.models.HTMLField()),
            ],
            options={
                'verbose_name_plural': 'Vacancy Instruction',
                'db_table': 'Vacancy Instruction',
            },
        ),
    ]
