# Generated by Django 5.0.4 on 2024-05-01 19:22

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='vacancy_content',
            field=tinymce.models.HTMLField(null=True),
        ),
    ]
