# Generated by Django 5.0.4 on 2024-05-01 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_app', '0002_vacancy_vacancy_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='files',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
