# Generated by Django 5.0.4 on 2024-05-09 21:24

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_app', '0003_remove_vacancy_files_vacancy_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=200)),
                ('contact', phonenumber_field.modelfields.PhoneNumberField(help_text='your contact number', max_length=128, region=None)),
                ('feedback', models.TextField()),
            ],
        ),
    ]
