# Generated by Django 5.0.4 on 2024-05-09 21:26

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_app', '0004_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='contact',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='your contact number', max_length=10, region=None),
        ),
    ]
