# Generated by Django 5.0.4 on 2024-05-10 17:58

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_app', '0005_alter_feedback_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('contact', phonenumber_field.modelfields.PhoneNumberField(help_text='your contact number', max_length=13, region=None)),
                ('address1', models.CharField(max_length=200)),
                ('address2', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=400)),
                ('province', models.CharField(max_length=400)),
                ('pcode', models.IntegerField(max_length=50)),
                ('membership', models.CharField(choices=[('GN', 'general'), ('LT', 'lifetime')], default='GN', max_length=2)),
                ('screenshot', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name_plural': 'Member',
                'db_table': 'Member',
            },
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name_plural': 'Contact'},
        ),
        migrations.AlterField(
            model_name='feedback',
            name='contact',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='your contact number', max_length=13, region=None),
        ),
        migrations.AlterModelTable(
            name='feedback',
            table='Contact',
        ),
    ]
