# Generated by Django 5.0.4 on 2024-05-11 10:50

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_app', '0006_member_alter_feedback_options_alter_feedback_contact_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('contact', phonenumber_field.modelfields.PhoneNumberField(help_text='your contact number', max_length=13, region=None)),
                ('address_1', models.CharField(max_length=200)),
                ('address_2', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(max_length=400)),
                ('state', models.CharField(max_length=400)),
                ('postal_code', models.IntegerField()),
                ('country', models.CharField(max_length=200)),
                ('donation_type', models.CharField(choices=[('GENERAL', 'general'), ('COVID', 'covid'), ('EARTHQUAKE', 'earthquake')], max_length=12)),
                ('amount', models.IntegerField()),
                ('screenshot', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name_plural': 'Donation',
                'db_table': 'Donation',
            },
        ),
        migrations.AlterField(
            model_name='member',
            name='address2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='membership',
            field=models.CharField(choices=[('GENERAL', 'general'), ('LIFETIME', 'lifetime')], default='GENERAL', max_length=9),
        ),
        migrations.AlterField(
            model_name='member',
            name='pcode',
            field=models.IntegerField(),
        ),
    ]
