# Generated by Django 5.0.4 on 2024-05-11 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_app', '0007_donation_alter_member_address2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='date',
            field=models.DateTimeField(auto_created=True, auto_now=True),
        ),
    ]
