# Generated by Django 5.0.4 on 2024-05-11 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_app', '0012_alter_feedback_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='date',
            field=models.DateTimeField(default='timezone.now', null=True),
        ),
    ]
