# Generated by Django 5.0.4 on 2024-05-11 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_app', '0013_alter_feedback_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='date',
            field=models.DateField(default='timezone.now', null=True),
        ),
    ]
