# Generated by Django 5.0.4 on 2024-05-11 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_app', '0014_alter_feedback_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='date',
            field=models.DateTimeField(default='timezone.now.strftime(%Y %M %D)', null=True),
        ),
    ]
