# Generated by Django 5.0.4 on 2024-05-11 13:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_app', '0017_alter_feedback_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='fname',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='fname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='lname',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='pcode',
            new_name='postal_code',
        ),
        migrations.AddField(
            model_name='member',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
