# Generated by Django 5.0.4 on 2024-05-11 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_app', '0018_rename_fname_feedback_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='contact',
            field=models.CharField(max_length=15),
        ),
    ]
