# Generated by Django 5.0.4 on 2024-05-13 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_app', '0019_alter_feedback_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donation',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Donation'},
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Contact'},
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Member'},
        ),
        migrations.AlterModelOptions(
            name='vacancy',
            options={'ordering': ['-id'], 'verbose_name_plural': 'vacancy'},
        ),
        migrations.AlterField(
            model_name='donation',
            name='contact',
            field=models.IntegerField(),
        ),
    ]
