# Generated by Django 5.0.4 on 2024-05-14 14:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_app', '0020_alter_donation_options_alter_feedback_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='status',
            field=models.CharField(choices=[('R', 'READ'), ('U', 'UNREAD')], default=django.utils.timezone.now, max_length=1),
            preserve_default=False,
        ),
    ]
