# Generated by Django 5.0.4 on 2024-05-14 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_app', '0023_alter_feedback_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='status',
            field=models.CharField(choices=[('R', 'Read'), ('U', 'Unread')], default='U', max_length=1),
        ),
    ]
