# Generated by Django 5.0.4 on 2024-05-14 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_app', '0024_alter_feedback_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='status',
            field=models.CharField(choices=[('C', 'Confirmed'), ('U', 'Unconfirmed')], default='U', max_length=1),
        ),
    ]
