# Generated by Django 5.0.4 on 2024-05-14 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_app', '0025_member_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='status',
            field=models.CharField(choices=[('C', 'Confirmed'), ('U', 'Unconfirm')], default='U', max_length=1),
        ),
        migrations.AlterField(
            model_name='member',
            name='status',
            field=models.CharField(choices=[('C', 'Confirmed'), ('U', 'Unconfirm')], default='U', max_length=1),
        ),
    ]
