# Generated by Django 5.0.4 on 2024-05-16 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_app', '0026_donation_status_alter_member_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='screenshot',
            field=models.ImageField(upload_to='images/payments/donation/'),
        ),
        migrations.AlterField(
            model_name='member',
            name='screenshot',
            field=models.ImageField(upload_to='images/payments/membership/'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/vacancy/'),
        ),
    ]
