# Generated by Django 5.0.4 on 2024-04-27 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pcommittee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('profile_pic', models.ImageField(upload_to='upload/')),
                ('position', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Executive Committee',
                'db_table': 'Executive Committee',
            },
        ),
        migrations.CreateModel(
            name='Xcommittee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('position', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Former Ex Committee',
                'db_table': 'Former Ex Committee',
            },
        ),
    ]
