# Generated by Django 5.0.4 on 2024-05-03 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_app', '0002_committee_delete_pcommittee_delete_xcommittee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committee',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
