# Generated by Django 5.0.4 on 2024-05-03 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_app', '0004_alter_committee_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committee',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
