# Generated by Django 5.0.4 on 2024-05-04 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_app', '0005_alter_committee_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Year_Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_frame', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Year Book',
                'db_table': 'Year Book',
            },
        ),
        migrations.AddField(
            model_name='committee',
            name='year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='team_app.year_book'),
        ),
    ]
