# Generated by Django 5.0.4 on 2024-05-04 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_app', '0006_year_book_committee_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='year_book',
            name='current_year',
            field=models.BooleanField(null=True),
        ),
    ]
