# Generated by Django 5.0.4 on 2024-05-04 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_app', '0008_alter_year_book_current_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='year_book',
            name='current_year',
            field=models.BooleanField(default=False),
        ),
    ]
