# Generated by Django 5.0.4 on 2024-05-12 14:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_app', '0009_alter_year_book_current_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='committee',
            old_name='position',
            new_name='education',
        ),
        migrations.RemoveField(
            model_name='committee',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='committee',
            name='start_date',
        ),
        migrations.AddField(
            model_name='committee',
            name='address',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='committee',
            name='profession',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
