# Generated by Django 5.0.4 on 2024-05-12 15:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_app', '0010_rename_position_committee_education_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='committee',
            name='position',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
    ]
