# Generated by Django 5.0.4 on 2024-05-12 16:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_app', '0011_committee_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='committee',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
    ]
