# Generated by Django 5.0.4 on 2024-05-13 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team_app', '0012_committee_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='committee',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Committee'},
        ),
    ]
