# Generated by Django 5.0.4 on 2024-05-14 18:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_app', '0013_alter_committee_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='committee',
            name='sub_title',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
