# Generated by Django 5.0.4 on 2024-05-14 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_app', '0014_committee_sub_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committee',
            name='sub_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
