# Generated by Django 5.0.4 on 2024-05-14 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team_app', '0015_alter_committee_sub_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='committee',
            name='sub_title',
        ),
    ]
