# Generated by Django 5.0.4 on 2024-05-16 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_app', '0016_remove_committee_sub_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committee',
            name='profile_pic',
            field=models.ImageField(upload_to='images/committees/profile_pic/'),
        ),
    ]
