# Generated by Django 5.0.3 on 2024-05-18 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_app', '0017_alter_committee_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submenu', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Sub Menu',
                'db_table': 'Sub Menu',
            },
        ),
    ]
