# Generated by Django 5.0.3 on 2024-05-19 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team_app', '0018_submenu'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submenu',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Sub Menu'},
        ),
    ]
