# Generated by Django 4.2.14 on 2024-07-27 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10)),
                ('content', models.ImageField(upload_to='images/alert_message/')),
            ],
            options={
                'verbose_name_plural': 'Alert Message',
                'db_table': 'Alert Message',
                'ordering': ['-id'],
            },
        ),
    ]
