# Generated by Django 4.2.14 on 2024-07-27 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alertmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertmessage',
            name='hide',
            field=models.BooleanField(default=False),
        ),
    ]
