# Generated by Django 4.2.14 on 2024-07-27 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alertmessage_hide'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertMessageHide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hidden', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Alert Message Hidden',
                'db_table': 'Alert Message Hidden',
            },
        ),
    ]
