# Generated by Django 5.0.4 on 2024-05-13 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_subscribe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slider',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Slider'},
        ),
        migrations.AlterModelOptions(
            name='subscribe',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Subscribe'},
        ),
    ]
