# Generated by Django 4.2.14 on 2024-08-01 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alertmessage_pic_message_alter_alertmessage_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertmessage',
            name='title',
            field=models.CharField(max_length=25),
        ),
    ]
