# Generated by Django 5.0.4 on 2024-05-16 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_slider_options_alter_subscribe_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='president',
            name='image',
            field=models.ImageField(upload_to='president/'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='picture',
            field=models.ImageField(upload_to='slider/'),
        ),
    ]
