# Generated by Django 5.0.3 on 2024-05-19 18:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_president_image_alter_slider_picture_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adversite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.FileField(null=True, upload_to='videos/advertisement/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])])),
            ],
            options={
                'verbose_name_plural': 'Advertisement',
                'db_table': 'Advertisement',
                'ordering': ['-id'],
            },
        ),
    ]
