# Generated by Django 5.0.3 on 2024-05-19 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_adversite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adversite',
            name='content',
            field=models.FileField(null=True, upload_to='videos/advertisement/'),
        ),
    ]
