# Generated by Django 5.0.3 on 2024-05-19 19:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_alter_adversite_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='adversite',
            name='picture',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images/president/'),
            preserve_default=False,
        ),
    ]
