# Generated by Django 5.0.3 on 2024-05-19 20:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_adversite_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='adversite',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
