# Generated by Django 5.0.3 on 2024-05-21 23:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_remove_adversite_name_remove_adversite_picture_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adversite',
            name='content',
        ),
        migrations.AddField(
            model_name='adversite',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images/advertise/'),
            preserve_default=False,
        ),
    ]
