# Generated by Django 4.2.14 on 2024-07-22 14:55

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_content', tinymce.models.HTMLField()),
            ],
            options={
                'verbose_name_plural': 'About SNS',
                'db_table': 'About SNS',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('sub_title', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('news_image', models.ImageField(blank=True, null=True, upload_to='images/news/')),
                ('brief', tinymce.models.HTMLField()),
                ('hide', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'News',
                'db_table': 'News',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_content', tinymce.models.HTMLField()),
            ],
            options={
                'verbose_name_plural': 'Terms and Condition',
                'db_table': 'Terms and Condition',
            },
        ),
        migrations.CreateModel(
            name='Vision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vision_content', tinymce.models.HTMLField()),
            ],
            options={
                'verbose_name_plural': 'Vision',
                'db_table': 'Vision',
            },
        ),
    ]
