# Generated by Django 5.0.4 on 2024-04-16 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='description',
            new_name='paragraph_1',
        ),
        migrations.AddField(
            model_name='about',
            name='paragraph_2',
            field=models.TextField(null=True),
        ),
    ]
