# Generated by Django 5.0.4 on 2024-04-16 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_app', '0002_rename_description_about_paragraph_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='paragraph_3',
            field=models.TextField(null=True),
        ),
    ]
