# Generated by Django 5.0.4 on 2024-04-16 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_app', '0003_about_paragraph_3'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('paragraph_title', models.CharField(max_length=100)),
                ('paragraph', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Vision',
                'db_table': 'Vision',
            },
        ),
    ]
