# Generated by Django 5.0.4 on 2024-04-23 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_app', '0005_maintitle_remove_vision_title_vision_main_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('main_title', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='about_app.maintitle')),
            ],
            options={
                'verbose_name_plural': 'Terms and Conditions',
                'db_table': 'Terms and Conditions',
            },
        ),
    ]
