# Generated by Django 5.0.4 on 2024-04-23 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_app', '0006_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
