# Generated by Django 5.0.4 on 2024-04-23 14:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_app', '0007_term_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintitle',
            name='quote',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
