# Generated by Django 5.0.4 on 2024-04-30 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_app', '0008_maintitle_quote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vision',
            name='paragraph',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='vision',
            name='paragraph_title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
