# Generated by Django 5.0.4 on 2024-04-30 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_app', '0010_rename_paragraph_title_vision_content_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vision',
            old_name='paragraph',
            new_name='content',
        ),
    ]
