# Generated by Django 5.0.4 on 2024-04-30 10:07

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_app', '0011_rename_paragraph_vision_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vision',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
