# Generated by Django 5.0.4 on 2024-04-30 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_app', '0012_alter_vision_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='paragraph_2',
        ),
        migrations.RemoveField(
            model_name='about',
            name='paragraph_3',
        ),
    ]
