# Generated by Django 5.0.4 on 2024-04-30 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_app', '0013_remove_about_paragraph_2_remove_about_paragraph_3'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name_plural': 'About SNS'},
        ),
        migrations.AlterModelTable(
            name='about',
            table='About SNS',
        ),
    ]
