# Generated by Django 5.0.4 on 2024-04-30 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_app', '0014_alter_about_options_alter_about_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='paragraph_1',
            new_name='about_content',
        ),
        migrations.RemoveField(
            model_name='about',
            name='title',
        ),
    ]
