# Generated by Django 5.0.4 on 2024-04-30 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_app', '0016_alter_about_about_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vision',
            name='main_title',
        ),
    ]
