# Generated by Django 5.0.4 on 2024-04-30 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_app', '0017_remove_vision_main_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vision',
            old_name='content',
            new_name='vision_content',
        ),
        migrations.RemoveField(
            model_name='vision',
            name='content_title',
        ),
    ]
