# Generated by Django 5.0.4 on 2024-04-30 18:21

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_app', '0018_rename_content_vision_vision_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='term',
            name='description',
        ),
        migrations.RemoveField(
            model_name='term',
            name='main_title',
        ),
        migrations.RemoveField(
            model_name='term',
            name='title',
        ),
        migrations.AddField(
            model_name='term',
            name='term_content',
            field=tinymce.models.HTMLField(null=True),
        ),
    ]
