# Generated by Django 5.0.4 on 2024-04-30 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_app', '0020_delete_maintitle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='term',
            options={'verbose_name_plural': 'Terms and Condition'},
        ),
        migrations.AlterModelTable(
            name='term',
            table='Terms and Condition',
        ),
    ]
