# Generated by Django 5.0.4 on 2024-05-01 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_app', '0021_alter_term_options_alter_term_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='term',
            name='image',
        ),
    ]
