# Generated by Django 5.0.4 on 2024-05-11 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appreciations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=200)),
                ('c_date', models.DateField()),
                ('files', models.FileField(upload_to='uploads/')),
            ],
            options={
                'verbose_name_plural': 'Appreciation',
                'db_table': 'Appreciation',
            },
        ),
        migrations.CreateModel(
            name='Laws',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=200)),
                ('c_date', models.DateField()),
                ('files', models.FileField(upload_to='uploads/')),
            ],
            options={
                'verbose_name_plural': 'Laws and Convention',
                'db_table': 'Laws and Convention',
            },
        ),
        migrations.CreateModel(
            name='References',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=200)),
                ('c_date', models.DateField()),
                ('files', models.FileField(upload_to='uploads/')),
            ],
            options={
                'verbose_name_plural': 'Reference',
                'db_table': 'Reference',
            },
        ),
    ]
