# Generated by Django 5.0.4 on 2024-05-11 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registrations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=200)),
                ('c_date', models.DateField()),
                ('files', models.FileField(upload_to='uploads/')),
            ],
            options={
                'verbose_name_plural': 'Registration',
                'db_table': 'Registration',
            },
        ),
    ]
