# Generated by Django 5.0.4 on 2024-05-11 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document_app', '0003_program_registration'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Program_Registration',
            new_name='Program_Registrations',
        ),
        migrations.AlterModelOptions(
            name='program_registrations',
            options={'verbose_name_plural': 'Program Registrations'},
        ),
        migrations.AlterModelTable(
            name='program_registrations',
            table='Program Registrations',
        ),
    ]
