# Generated by Django 5.0.4 on 2024-05-11 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document_app', '0004_rename_program_registration_program_registrations_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Program_Registrations',
        ),
    ]
