# Generated by Django 5.0.4 on 2024-05-11 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document_app', '0005_delete_program_registrations'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registrations',
            options={},
        ),
        migrations.AlterModelTable(
            name='registrations',
            table=None,
        ),
    ]
