# Generated by Django 5.0.4 on 2024-05-14 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_app', '0007_program_registrations_alter_registrations_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='program_registrations',
            name='status',
            field=models.CharField(choices=[('C', 'Confirmed'), ('U', 'Unconfirm')], default='U', max_length=1),
        ),
    ]
