# Generated by Django 5.0.4 on 2024-05-16 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_app', '0008_program_registrations_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appreciations',
            name='f_name',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='appreciations',
            name='files',
            field=models.FileField(max_length=254, upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='laws',
            name='f_name',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='laws',
            name='files',
            field=models.FileField(max_length=254, upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='references',
            name='f_name',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='references',
            name='files',
            field=models.FileField(max_length=254, upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='registrations',
            name='f_name',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='registrations',
            name='files',
            field=models.FileField(max_length=254, upload_to='files/'),
        ),
    ]
