# Generated by Django 5.0.4 on 2024-05-16 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_app', '0009_alter_appreciations_f_name_alter_appreciations_files_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appreciations',
            name='files',
            field=models.FileField(max_length=254, upload_to='files/appreciations/'),
        ),
        migrations.AlterField(
            model_name='laws',
            name='files',
            field=models.FileField(max_length=254, upload_to='files/laws/'),
        ),
        migrations.AlterField(
            model_name='program_registrations',
            name='screenshot',
            field=models.ImageField(upload_to='images/payments/program_registration/'),
        ),
        migrations.AlterField(
            model_name='references',
            name='files',
            field=models.FileField(max_length=254, upload_to='files/references/'),
        ),
        migrations.AlterField(
            model_name='registrations',
            name='files',
            field=models.FileField(max_length=254, upload_to='files/registrations/'),
        ),
    ]
