# Generated by Django 5.0.3 on 2024-05-26 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_app', '0010_alter_appreciations_files_alter_laws_files_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appreciations',
            name='c_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='laws',
            name='c_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='program_registrations',
            name='date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='references',
            name='c_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='registrations',
            name='c_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
